version: '3.1'

services:
  db:
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: strong_password
  app:
    build: .
    restart: always
    depends_on:
      - "db"
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/postgres
      DATABASE_USER: postgres
      DATABASE_PASS: strong_password
    ports:
      - 8080:8080